# -*- coding: utf-8 -*-
"""ejercicio5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a0GLcm5qAXeYIPHv_OCZG193OrynfBNF
"""

from lista import *

# lista lista ... lista N -> str
# Queremos desarrollar una función que nos sume los valores de una lista

def suma(unaLista):

# Primero se define el caso cuando la lista es vacia
# Se recurre a la función vacia() del modulo "lista"
  if vacia(unaLista):
    return 0

# Luego definimos el otro caso, cuando la lista no es vacia
  else:
# Definimos el primer valor que se debe sumar, que corresponde a la cabeza de nuestra lista, es decir al primer valor de esta
    valor1 = cabeza(unaLista)
# Lurgo se define el resto (correspondiente a la cola de nuestra lista inicial) como "ListaRestante"
    ListaRestante = cola(unaLista)
# Ya que la función debe servir para cualquier cantidad de listas debemos definirla de manera recursiva
    return valor1 + suma(ListaRestante)

# Tests
lista0 = None
lista1 = lista(0, lista(3, lista(4, None)))
lista2 = lista(4, lista(8, lista1))
assert suma(lista1)==7
assert suma(lista2)==19
assert suma(lista0)==0