# -*- coding: utf-8 -*-
"""Ejercicio06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f5Ujg5zl8deAAVnUjEAXjsWZ8_P9bWWO
"""

# primero, importamos las funciones auxiliares que necesitaremos
import estructura
from abstraccion import *
from lista import *

# dada una lista de elementos de tipo "producto", denido como una estructura con los campos "nombre",
# "precio" y "cantidad" de la siguiente manera:
estructura.crear( "producto","nombre precio cantidad")

# totalCarrito: lista(producto) -> int
# buscamos una función que, a partir de una lista de productos, calcule el costo total de la compra
# esto es, la sumatoria de producto por cantidad en la lista "carrito"
# por ejemplo, lista(producto("chocolate",1200,3), lista(producto("destacadores", 750, 6),lista(producto("bidon de agua",3000,1), None)))
# deberia retornar 11100
def totalCarrito(unaLista):
  if vacia(unaLista):
    return 0
  else:
    producto=cabeza(unaLista)
    return producto.precio*producto.cantidad + totalCarrito(cola(unaLista))

# Programa principal
carrito = lista(producto("cafe", 2500, 2), lista(producto("aceite", 5000, 1), None))
print (totalCarrito(carrito))

# Tests
carrito2 = lista(producto("chocolate",1200,3), lista(producto("destacadores", 750, 6),lista(producto("bidon de agua",3000,1), None)))
assert totalCarrito(carrito2) == 11100