# -*- coding: utf-8 -*-
"""Ejercicio8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14WUN05sw0VJXdpVidsAZ_95jcHAZhtp4
"""

# formatear: nombres -> lista
# Queremos una función que a partir de una lista de nombres (con el primer nombre y el primer apellido) no necesariamente
# bien escrita (con mayúsculas y minúsculas intercambiadas) debe retornar una lista con los nombres en orden alfabético (por el
# primer nombre) y escrita correctamente
# ej: ['XimEna OlivOS','Claudia GoMez', 'Maria Smith','andrea Pinto','jorge rodriguez', 'peDro orTuzar', 'BEATRIZ OH'] debería 
# retornar ['Andrea Pinto','Beatriz Oh','Claudia Gomez','Jorge Rodriguez','Maria Smith','Pedro Ortuzar','Ximena Olivos']

def formatear(lista):
    l=[]   
    
    def corregir(nombre):
        l=len(nombre)
        s=nombre.find(" ")
        n=nombre.lower()
        p=nombre[0]
        a=nombre[s+1]
        x=p.upper()+n[1:s]+" "+a.upper()+n[s+2:l]
        return x
     
    for n in lista:
      n=corregir(n)
      l.append(n.strip()) #agregamos elementos a la lista vacia l
      l.sort()
    return l

# Tests
listaNombres=['XimEna OlivOS','Claudia GoMez', 'Maria Smith','andrea Pinto','jorge rodriguez', 'peDro orTuzar', 'BEATRIZ OH']
assert formatear(listaNombres)==['Andrea Pinto','Beatriz Oh','Claudia Gomez','Jorge Rodriguez','Maria Smith','Pedro Ortuzar','Ximena Olivos']