# -*- coding: utf-8 -*-
"""tarea1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDAskGNjT8jmxyZk8epclEuOsZGuY3qT
"""

import cachipunls

#Se da la bienvenida al juego
def Juego():
  print('Bienvenido al juego del cachipún-lagarto-Spock!!!')
  modalidad=int(input('Ingrese la modalidad en que desea jugar, Jugador vs Computador (1) o Computador vs Computador (2): '))
  if modalidad==1:
    print('La modalidad escogida es Jugador vs Computador')

    #Se pide al primer jugador que ingrese su jugada
    y= str(input('Jugador 1 ingrese la jugada papel,tijeras,piedra,lagarto o spock: '))

    #Se transforma su jugada (string) a int
    jugada1=codificaJugada(y)

    # Se expone la jugada del computador
    jugada2a=cachipunls.generaJugadaComputador()
    # Se transforma la jugada del computador de número a palabra
    jugada2b=cachipunls.decodificaJugada(jugada2a)
    print ('Jugador 2 (computador) juega', jugada2b)

    # Se calcula e imprime el resultado del juego
    resultado=ganaJugada(jugada1,jugada2a)
    resultado2=traducciónganaJugada(resultado)
    print (resultado2)

  elif modalidad==2:
    print('La modalidad escogida es Computador vs Computador')

    # Jugada 1
    jugada1a=cachipunls.generaJugadaComputador()
    # Se transforma la jugada del computador de número a palabra
    jugada1b=cachipunls.decodificaJugada(jugada1a)
    print ('Jugador 1 (computador) juega', jugada1b)

    # Jugada 2
    jugada2a=cachipunls.generaJugadaComputador()
    # Se transforma la jugada del computador de número a palabra
    jugada2b=cachipunls.decodificaJugada(jugada2a)
    print ('Jugador 2 (computador) juega', jugada2b)

    # Se calcula e imprime el resultado del juego
    resultado=cachipunls.ganaJugada(jugada1a,jugada2a)
    resultado2=traducciónganaJugada(resultado)
    print (resultado2)

def traducciónganaJugada(resultado):
  if resultado == 0:
    return '¡Empate!'
  if resultado == 1:
    return '¡Gana Jugador 1!'
  if resultado == -1:
    return '¡Gana Jugador 2!'

Juego()